apiVersion: v1
kind: Service
metadata:
  name: threat-api-svc
  labels:
    app: threat-api
    tier: backend
spec:
  type: NodePort 
  ports:
    - port: 8000
      targetPort: 8000
      NodePort: 30080
  selector:
    app: threat-api
    tier: backend